### ISSUE TITLE
is yarn needed?

### ISSUE THREAD

**Issue by nickerso** [nih-sparc/data-portal#18]
Installing and running current master locally on a windows machine I followed the instructions in the README and the site is up and running without obvious errors. Whereas in the wiki page it mentions needing to install yarn - is that just for Macs? or the `npm run ...` and/or `pip install -r requirements.txt` will take care of it?

**Comment by jwagenaar** [comment]
I think you can either use yarn, or npm.

**Comment by jwagenaar** [comment]
I removed the yarn install instructions from the wiki as it is not a requirement.
