### ISSUE TITLE
Encounter blackfynn.base.UnauthorizedException error

### ISSUE THREAD

**Issue by alan-wu** [nih-sparc/data-portal#20]
Hi, I followed the instructions and I encounter Encounter blackfynn.base.UnauthorizedException error when trying to access localhost:5000. I try it with both Python3.5 and 3.6 on two different Ubuntu16.04 VirtualBox instances.

Should I be using a specific version of Python or on a specific platform?

I can provide Traceback if it helps.

**Comment by alan-wu** [comment]
Everything else is working fine after I comment out those few lines that initialize Blackfynn.

**Comment by nickerso** [comment]
Maybe worth pointing out that this doesn't seem to be an issue building/deploying the data portal on my windows machine...

**Comment by alan-wu** [comment]
Jesse also experiences the same problem and he is building/deploying on a windows machine.

**Comment by dbrnz** [comment]
I've got this exact issue under macOS.

**Comment by dbrnz** [comment]
Hmm @alan-wu, @nickerso, all that is needed is to set `BLACKFYNN_API_TOKEN` and `BLACKFYNN_API_SECRET` in `config.py` using a key-pair generated as per the [instructions](http://help.blackfynn.com/developers/configuration/creating-an-api-key-for-the-blackfynn-clients)...

**Comment by jwagenaar** [comment]
Are you still running into this issue? As mentioned above, you'll have to make sure you have the proper API_TOKEN and SECRET setup as environment variables when running the webapp locally (make sure you don't add those to a file that is committed to Github) These variables are automatically set in the production environment.

**Comment by dbrnz** [comment]
@jwagenaar, shouldn't this be mentioned in the notes about running in development mode??

**Comment by jwagenaar** [comment]
Totally, I can absolutely add this.
