### ISSUE TITLE
Information regarding the Heroku envirnoment

### ISSUE THREAD

**Issue by alan-wu** [nih-sparc/data-portal#22]
I would like to know more about the Heroku environment the data portal going to be deployed on as we have this server backend that we want to precompile for the Heroku platform.
Is there any information available and should  this information be made available somewhere on the wiki?

**Comment by jwagenaar** [comment]
Hi Alan, 
Can you clarify a bit more what you mean by backend server?

**Comment by alan-wu** [comment]
Hi Joost,I mean the backend services required for some of our apps to run such as the The customised scaffold generation.Some of these services utilise an in-house built C/C++ library wrapped in Python which will be made available on Pip later on.Our current plan if possible is to deploy these services on the Heroku platform and access them through reverse proxy in the map flask blueprints.That is the reason we would like to have more information regarding the environment and make a prebuilt library based on that.Thanks a lot.On 20 Mar 2019 3:20 a.m., Joost Wagenaar <notifications@github.com> wrote:Hi Alan,
Can you clarify a bit more what you mean by backend server?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


On 20 Mar 2019 3:20 a.m., Joost Wagenaar <notifications@github.com> wrote:Hi Alan,
Can you clarify a bit more what you mean by backend server?

**Comment by chrisbaglieri** [comment]
Hi Alan,

If by services you mean a library versus an API deployed elsewhere that you can invoke from within the data portal, which is what I think you have described above, you can certainly bundle this code in the Flask app directly. Heroku is flexible and a layer focused on application hosting, deployment and scaling. Think of it as basically a tool belt for making deploying applications very simple and easy to scale. It is completely agnostic of the underlying technologies you use.

If it would be helpful, happy to hop on a call and work through the challenge you are experiencing more deeply.

**Comment by nickerso** [comment]
Thanks @chrisbaglieri  and @jwagenaar - maybe just to clarify a bit, the MAPcore organ scaffolds can be created and modified "on the fly" using our finite element C++ code. The python bindings for this library can (and are) used with Flask to provide the web services that the UI will need to support our use-cases for the data portal. We are working towards providing a pip installable version of this C++ library with Python bindings so that it is simply another package listed in the portal requirements, but for this to work we need to make sure that the binary python wheel is built for the appropriate target platform - we generally target Ubuntu flavours of linux, but need to make sure that we are building wheels for the underlying platform that the portal is deployed to on Heroku - python version, std C/gnu/kernel versions, etc.

Not sure if that helps clarify what we are after?

**Comment by chrisbaglieri** [comment]
Ah, very helpful @nickerso. So we will need to think through this, certainly. This is not a Heroku challenge per say, it's an issue with deploying to a platform as a service versus infrastructure as a service. Nevertheless, I'm sure we can figure out a path forward. Let me do some digging on this as I am certain we are not the first to encounter this. If I recall, Heroku does specific the flavor of Linux they use. I'll circle back on this shortly... thanks!

**Comment by chrisbaglieri** [comment]
@nickerso @alan-wu here's additional details that I think gets you what you need. Heroku has the concept of stacks (https://devcenter.heroku.com/articles/stack). The data portal is deployed to the default stack, which is supported (at least) through 2023: Ubuntu 18.04. If you compile against that you should be all set. The same goes for the version of python that is installed. If it isn't already, that can be specific in the applications procfile or requirements.txt. Does this make sense?

I will add, I do think the longer term goal of handling the dependency in a more standard manner (e.g. through pip) is probably the way to go and something to plan for.

**Comment by alan-wu** [comment]
Thanks @chrisbaglieri we intend to have everything on pip including the python binding of c/c++ APIs mentioned above available for major platforms on pip as well.
One more question, which version of Python is the flask server on Heroku going to run on?
We have made a decision to stop supporting Python2 for MAPcore python packages from this point onward as it is at the end of life.

By the way, should we have the information regarding the Heroku stacks available somewhere on the wiki?

Once again, many thanks.

**Comment by chrisbaglieri** [comment]
@alan-wu I love the idea of tossing the Heroku stack on the wiki, feel free to make that commit. With regards to Python version, by default, the version on Heroku is 3.6.8: [https://devcenter.heroku.com/articles/python-support#specifying-a-python-version](url)

**Comment by alan-wu** [comment]
@chrisbaglieri I would like to but I do not have the right permission to do so.

**Comment by jwagenaar** [comment]
Hi Alan,
let me have a look at that, you should definitely be able to do so. I am
traveling today but will reach out when I know more.
Joost

______________________

Joost Wagenaar, Ph.D. | VP, Scientific Applications | Blackfynn Inc.

joost@blackfynn.com | Phone:  (412) 726-9859

**Comment by jwagenaar** [comment]
Hey Alan,
I added you as a collaborator, you should be able to edit the wiki now.

**Comment by alan-wu** [comment]
@jwagenaar @chrisbaglieri Thanks, I have added a little section on the Technology page about Heroku stacks and python information.
