### ISSUE TITLE
Upgrade (or remove) FontAwesome from base template

### ISSUE THREAD

**Issue by dbrnz** [nih-sparc/data-portal#23]
The MAP-CORE flatmap application makes use of the current version of FontAwesome, namely 5.8.0, whereas I see that the data portal loads version 4.7.0 (in `./templates/base.html`). To ensure we don't run into compatibility issues could either the current version be used or (better??) simply have apps load their own version when needed?

**Comment by jwagenaar** [comment]
That sounds good to me. I'll remove it from base.html
