### ISSUE TITLE
`bundle.js` is not found.

### ISSUE THREAD

**Issue by dbrnz** [nih-sparc/data-portal#38]
When running a newly created development environment using the `master` branch, installed as per the Wiki, the browser cannot find `bundle.js`:

<img width="529" alt="Screen Shot 2019-06-25 at 12 36 44 PM" src="https://user-images.githubusercontent.com/239220/60060789-6d5fa380-9746-11e9-8208-119e7ec7792b.png">

**Comment by alan-wu** [comment]
I just figure out that you also need to build the shared modul as followed "npm run dev-build-shared".
The documentation should be updated to reflect this additional step.

**Comment by alan-wu** [comment]
I have updated the wiki and also submit a pull request to the README.md here #40.

**Comment by dbrnz** [comment]
Thanks, building the shared module has fixed this.
