### ISSUE TITLE
SPARC Portal Footer Updates (NIH feedback)

### ISSUE THREAD

**Issue by lguercio** [nih-sparc/data-portal#76]
Clone footer from sparc.science page, with the following edits:
1) Change contact email address (i.e. remove Gene and create a new email and contact person for SPARC Portal activities)
2) Under "Learn More", change SPARC Portal for SPARC.science
3) Remove FAQs 
4) Update and replace Privacy Policy
5) Website Feedback link should direct to Portal survey
6) Remove copyright information

**Comment by jwagenaar** [comment]
Done (DAT-Core)
